version: "3.9"  # optional since v1.27.0
services:
  api:
    image: millegalb/aqua.api:1.0.0
    build:
      context: BackEnd.Net/Aqua
      dockerfile: Dockerfile
    ports:
      - "3088:3088"
    networks:
      - sky
    links:
      - controlls
  web:
    image: millegalb/aqua.web:1.0.0
    build:
      context: BackEnd.Net/Aqua/Aqua.Web
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ./UI/packages/aqua/dist:/app/wwwroot
    networks:
      - sky
    links:
      - controlls
      - api
  controlls:
    image: millegalb/form-controlls:1.0.0
    build:
      context: BackEnd.Net/Controlls/src
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    volumes:
      - ./UI/packages/form-controls/dist:/app/wwwroot
    networks:
      - sky

networks:
  sky:
