declare module "ts-header/Header";
declare module "ts-aqua-wert/NeueMessung";
declare module "ts-aqua-liste/AquaListe";
declare module "ts-control/DaSelect";
declare module "ts-control/DaCheckbox";
declare module "ts-control/DaDatePicker";
declare module "ts-control/DaRadioButton";
declare module "ts-control/DaTextInput";
declare module "ts-app-store/store";