name: .NET

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Dingenskirchen.sln
      working-directory: ./BackEnd.Net
    - name: Build
      run: dotnet build --no-restore ./Dingenskirchen.sln
      working-directory: ./BackEnd.Net
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Dingenskirchen.sln
      working-directory: ./BackEnd.Net

